import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1b24",
        "surface-container-high": "#eae6f4",
        background: "#fcf8ff",
        "on-tertiary-fixed": "#351000",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-container": "#ffd2be",
        on: "#1b1b24",
        "surface-container-low": "#f5f2ff",
        "on-secondary-container": "#5c647a",
        "on-tertiary": "#ffffff",
        outline: "#777587",
        error: "#ba1a1a",
        tertiary: "#7e3000",
        "primary-container": "#4f46e5",
        "surface-container": "#f0ecf9",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd8e5",
        secondary: "#565e74",
        "inverse-primary": "#c3c0ff",
        "secondary-container": "#dae2fd",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb695",
        surface: "#fcf8ff",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#ffdbcc",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-container": "#a44100",
        primary: "#3525cd",
        "on-secondary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3323cc",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-container": "#dad7ff",
        "secondary-fixed": "#dae2fd",
        "surface-container-highest": "#e4e1ee",
        "surface-bright": "#fcf8ff",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e1ee",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary-fixed": "#0f0069",
        "inverse-on-surface": "#f3effc",
        "error-container": "#ffdad6",
        "inverse-surface": "#302f39",
        "on-surface-variant": "#464555",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
};
export default config;